parameters:
services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\Message\Event\Product\ProductCreatedEvent:
        tags:
            - { name: 'enqueue.processor', topic: 'inventory-service.product_created' }
    App\Message\Event\Product\ProductUpdatedEvent:
        tags:
            - { name: 'enqueue.processor', topic: 'inventory-service.product_updated' }
    App\Message\Event\Product\ProductRemovedEvent:
        tags:
            - { name: 'enqueue.processor', topic: 'inventory-service.product_removed' }